### PR TITLE
21  Ignore kubb generated files in linter

### LINKED ISSUE #21: Ignore kubb generated files in linter
# Describe
The lint command is filled with spam from the automatically created files in the `gen` folder. We don't have control over these files and can't fix the warnings. Meanwhile, they are obfuscating the errors/warnings in the source control that we can control. We should ignore the files in the `gen` folder

## Acceptance criteria
- [x] the lint command in the npm scripts ignores the gen folder
- [x] the lint command in the precommit hook ignore the gen folder

### PR DESCRIPTION
**Pull request by horatiorosa**
#### Description
In `package.json`
   - updated lint script to ignore `app/gen`
   - updated `lint-staged` setting to ignore `app/gen` folder in pre-commit hook
   -  use ignorePattern config to skip gen files
   -  regenerated kubb files

#### Tickets
Closes #21

### CODE REVIEW

**Review by TangoYankee — CHANGES_REQUESTED** [review]
Hmm, I seem to be affected by gremlins now. Will follow up when there is more time.

**Comment by TangoYankee** [comment]
> Hmm, I seem to be affected by gremlins now. Will follow up when there is more time.

It seems the ignore-paths flag isn't designed to handle more than single files? https://github.com/eslint/eslint/issues/9794

**Comment by horatiorosa** [comment]
@TangoYankee  So what do we do? Close without merging or is there a different solution we can look at?

**Comment by horatiorosa** [comment]
Closing in favor of [this PR](https://github.com/NYCPlanning/ae-cp-map/pull/52)

**Pull request closed without merging**
